services:
  web_client:
    build: ./client
    command: ./npms.sh
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
    environment:
      AUTH0_CLIENT_ID: FW0RejixVf54alwZA8ZOWn5py327gMxW
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2G
  mongodb:
    image: mongo
    restart: always   
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb/mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/       
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password 
    networks:
      - mongo-network      
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M      
volumes:
  pgdata: 
  mongodata:
networks:
  mongo-network:
